github: https://github.com/joerobmunoz

blog: blog # name of the blog route

math: katex # options: katex, mathjax, false

cdn:
  normalize: '//cdn.jsdelivr.net'    
  carbon: ''
  duoshuo: '//static.duoshuo.com'
  jQuery: '//cdn.jsdelivr.net'
  pjax: '//cdn.jsdelivr.net'
  mathjax: '//cdn.mathjax.org'
  fancybox: '//cdn.jsdelivr.net'
  katex: '//cdn.jsdelivr.net'